pragma solidity 0.5.16;

/// @title Basic Leveraged Strategy
/// @author Chainvisions
/// @notice Basic leveraged strategy contract

/*
* This contract contains a skeleton implementation of a leveraged strategy. All functions that a position interacts with
* can be found here. Something to note is that the strategy is not designed to execute any functions of it's own. Instead,
* the system is designed where a "Position" that utilizes the strategy delegates calls to this contract. By themselves, strategies
* cannot be adopted by any positions. For a position to utilize a strategy, it needs to be added to the list of strategies in the Controller.
* This also prevents malicious strategies from being executed.
*/

contract Strategy {
    // This function should harvest yields generated by the
    // position and it should also liquidate these rewards
    // and compound them. This is also where you would charge
    // performance fees. These fees must be read from the Controller
    // and sent to it on harvest.
    function harvest() public {

    }
}